"""Make bio nullable

Revision ID: 46478bdb51b7
Revises: d44a6313e737
Create Date: 2025-04-14 19:30:36.173240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46478bdb51b7'
down_revision = 'd44a6313e737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_flagged')

    # ### end Alembic commands ###
