"""Make bio nullable

Revision ID: 81761115497c
Revises: c4629ea73b23
Create Date: 2025-04-14 19:10:48.544803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81761115497c'
down_revision = 'c4629ea73b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
